services:
  gluetun-sync:
    image: harbor.local.abbottland.io/library/gluetun-sync:0.0.10
    profiles:
      - e2e
    build:
      context: ../../
      dockerfile: docker/pnpm-turbo.Dockerfile
      args:
        BASE_IMAGE: harbor.local.abbottland.io/library/node-22-alpine:1.0.0
        PROJECT_DIR: apps/
        PROJECT: gluetun-sync
    ports:
      - '4000:4000'
    environment:
      # Gluetun Sync Config
      - PORT=4000
      - SHOW_CONFIG=true
      - TZ=America/Chicago
      - CRON_EXPRESSION=*/20 * * * * # Run every 20 minutes
      # Gluetun API Config
      - GLUETUN_API_HOST=http://gluetun:8000
      # QbitTorrent API Config
      - QBITTORRENT_API_HOST=http://qbittorrent:8080
      - QBITTORRENT_USERNAME=admin
      - QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD}
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:4000/healthz']
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 4s
    depends_on:
      gluetun:
        condition: service_healthy
      qbittorrent:
        condition: service_healthy

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    ports:
      - '8000:8000'
      - '8888:8888'
      - '8388:8388/tcp'
      - '8388:8388/udp'
    environment:
      - TZ=America/Chicago
      - VPN_SERVICE_PROVIDER=private internet access
      - SERVER_REGIONS=CA Toronto
      - PORT_FORWARD_ONLY=true
      - VPN_PORT_FORWARDING=on
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ['CMD', 'nc', '-z', 'localhost', '8000']
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 5s

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - '8080:8080'
    environment:
      - QBITTORRENT_USERNAME=admin
      - QBITTORRENT_API_HOST=http://gluetun:8080
      - QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD}
    volumes:
      # Default password in this configuration is set to Password123
      - ./docker/conf/qBittorrent/qBittorrent.conf:/config/qBittorrent/qBittorrent.conf
    healthcheck:
      test: ['CMD', 'curl', '-fS', 'http://localhost:8080']
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 5s
