// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import { gotoStory, STANDARD_VIEWPORT, SCREENSHOT_OPTIONS } from '../../../tests/playwright-helpers';

test.describe('Card Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });


  test('default', async ({ page }) => {
    await gotoStory(page, 'components-card--default');
    await expect(page).toHaveScreenshot('components-card--default.png', SCREENSHOT_OPTIONS);
  });


  test('primary', async ({ page }) => {
    await gotoStory(page, 'components-card--primary');
    await expect(page).toHaveScreenshot('components-card--primary.png', SCREENSHOT_OPTIONS);
  });


  test('secondary', async ({ page }) => {
    await gotoStory(page, 'components-card--secondary');
    await expect(page).toHaveScreenshot('components-card--secondary.png', SCREENSHOT_OPTIONS);
  });


  test('large', async ({ page }) => {
    await gotoStory(page, 'components-card--large');
    await expect(page).toHaveScreenshot('components-card--large.png', SCREENSHOT_OPTIONS);
  });


  test('large-primary', async ({ page }) => {
    await gotoStory(page, 'components-card--large-primary');
    await expect(page).toHaveScreenshot('components-card--large-primary.png', SCREENSHOT_OPTIONS);
  });


});

