// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('EdgeDrawer Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('closed', async ({ page }) => {
    await gotoStory(page, 'components-edgedrawer--closed');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-edgedrawer--closed.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('open', async ({ page }) => {
    await gotoStory(page, 'components-edgedrawer--open');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-edgedrawer--open.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
