// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import { gotoStory, STANDARD_VIEWPORT, SCREENSHOT_OPTIONS } from '../../../tests/playwright-helpers';

test.describe('Panel Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });


  test('default', async ({ page }) => {
    await gotoStory(page, 'components-panel--default');
    await expect(page).toHaveScreenshot('components-panel--default.png', SCREENSHOT_OPTIONS);
  });


  test('primary-outlined', async ({ page }) => {
    await gotoStory(page, 'components-panel--primary-outlined');
    await expect(page).toHaveScreenshot('components-panel--primary-outlined.png', SCREENSHOT_OPTIONS);
  });


  test('primary-dots', async ({ page }) => {
    await gotoStory(page, 'components-panel--primary-dots');
    await expect(page).toHaveScreenshot('components-panel--primary-dots.png', SCREENSHOT_OPTIONS);
  });


});

