// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import { gotoStory, STANDARD_VIEWPORT, SCREENSHOT_OPTIONS } from '../../../tests/playwright-helpers';

test.describe('ButtonShowcase Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });


  test('colors-and-variants', async ({ page }) => {
    await gotoStory(page, 'showcase-button--colors-and-variants');
    await expect(page).toHaveScreenshot('showcase-button--colors-and-variants.png', SCREENSHOT_OPTIONS);
  });


});

