// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('DefaultNode Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('default', async ({ page }) => {
    await gotoStory(page, 'diagrams-defaultnode--default');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'diagrams-defaultnode--default.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
