// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import { gotoStory, STANDARD_VIEWPORT, SCREENSHOT_OPTIONS } from '../../../tests/playwright-helpers';

test.describe('Typography Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });


  test('body-2', async ({ page }) => {
    await gotoStory(page, 'components-typography--body-2');
    await expect(page).toHaveScreenshot('components-typography--body-2.png', SCREENSHOT_OPTIONS);
  });


  test('body-1', async ({ page }) => {
    await gotoStory(page, 'components-typography--body-1');
    await expect(page).toHaveScreenshot('components-typography--body-1.png', SCREENSHOT_OPTIONS);
  });


  test('caption', async ({ page }) => {
    await gotoStory(page, 'components-typography--caption');
    await expect(page).toHaveScreenshot('components-typography--caption.png', SCREENSHOT_OPTIONS);
  });


  test('small', async ({ page }) => {
    await gotoStory(page, 'components-typography--small');
    await expect(page).toHaveScreenshot('components-typography--small.png', SCREENSHOT_OPTIONS);
  });


  test('button', async ({ page }) => {
    await gotoStory(page, 'components-typography--button');
    await expect(page).toHaveScreenshot('components-typography--button.png', SCREENSHOT_OPTIONS);
  });


  test('h-1', async ({ page }) => {
    await gotoStory(page, 'components-typography--h-1');
    await expect(page).toHaveScreenshot('components-typography--h-1.png', SCREENSHOT_OPTIONS);
  });


  test('h-2', async ({ page }) => {
    await gotoStory(page, 'components-typography--h-2');
    await expect(page).toHaveScreenshot('components-typography--h-2.png', SCREENSHOT_OPTIONS);
  });


  test('h-3', async ({ page }) => {
    await gotoStory(page, 'components-typography--h-3');
    await expect(page).toHaveScreenshot('components-typography--h-3.png', SCREENSHOT_OPTIONS);
  });


  test('h-4', async ({ page }) => {
    await gotoStory(page, 'components-typography--h-4');
    await expect(page).toHaveScreenshot('components-typography--h-4.png', SCREENSHOT_OPTIONS);
  });


  test('h-5', async ({ page }) => {
    await gotoStory(page, 'components-typography--h-5');
    await expect(page).toHaveScreenshot('components-typography--h-5.png', SCREENSHOT_OPTIONS);
  });


  test('h-6', async ({ page }) => {
    await gotoStory(page, 'components-typography--h-6');
    await expect(page).toHaveScreenshot('components-typography--h-6.png', SCREENSHOT_OPTIONS);
  });


});

