// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('CautionTape Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('default', async ({ page }) => {
    await gotoStory(page, 'components-cautiontape--default');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-cautiontape--default.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('custom-label', async ({ page }) => {
    await gotoStory(page, 'components-cautiontape--custom-label');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-cautiontape--custom-label.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('straight', async ({ page }) => {
    await gotoStory(page, 'components-cautiontape--straight');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-cautiontape--straight.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('over-content', async ({ page }) => {
    await gotoStory(page, 'components-cautiontape--over-content');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-cautiontape--over-content.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
