kind: pipeline
name: ci
type: docker
platform:
  os: linux
  arch: arm64

trigger:
  event:
    - push
environment:
    NPM_REGISTRY: verdaccio.nas.local.abbottland.io
    NPM_REGISTRY_PROTO: https
steps:
  - name: git fetch
    image: alpine/git
    commands:
      - git fetch --tags

  - name: Restore packages with Yarn
    image: registry.nas.local.abbottland.io/drone-node-gh-cli:2.0.1
    volumes:
      - name: yarn_cache
        path: /tmp/yarn_cache
      - name: node_module_cache
        path: /drone/src/node_modules
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
      - yarn config set cache-folder /tmp/yarn_cache
      - yarn --frozen-lockfile

  - name: Run Build
    image: registry.nas.local.abbottland.io/drone-node-gh-cli:2.0.1
    volumes:
      - name: yarn_cache
        path: /tmp/yarn_cache
      - name: node_module_cache
        path: /drone/src/node_modules
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
      - nx graph --file=output.json
      - nx affected --target build --base=origin/main --skip-nx-cache
  - name: Run Tests
    image: registry.nas.local.abbottland.io/drone-node-gh-cli:2.0.1
    volumes:
      - name: yarn_cache
        path: /tmp/yarn_cache
      - name: node_module_cache
        path: /drone/src/node_modules
    commands:
      - nx affected --target test --base=origin/main

volumes:
  - name: yarn_cache
    host:
      path: /var/lib/cache/yarn
  - name: node_module_cache
    host:
      path: /var/lib/cache/node_modules

image_pull_secrets:
  - REG_CRED

---

kind: pipeline
name: release
type: docker

depends_on:
  - ci

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - main
  ref:
    exclude:
      - refs/tags/*

environment:
  NPM_REGISTRY: verdaccio.nas.local.abbottland.io
  NPM_REGISTRY_PROTO: https

steps:
  - name: Restore packages with Yarn
    image: registry.nas.local.abbottland.io/drone-node-gh-cli:2.0.1
    volumes:
      - name: yarn_cache
        path: /tmp/yarn_cache
      - name: node_module_cache
        path: /drone/src/node_modules
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN
    commands:
      - yarn config set cache-folder /tmp/yarn_cache
      - yarn --frozen-lockfile
          
  - name: Semanticially Version packages based on affected changes
    image: registry.nas.local.abbottland.io/drone-node-gh-cli:2.0.1
    volumes:
      - name: yarn_cache
        path: /tmp/yarn_cache
      - name: node_module_cache
        path: /drone/src/node_modules
    environment:
      NPM_TOKEN:
        from_secret: NPM_TOKEN
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - git remote remove origin
      - git remote add origin https://$GITHUB_TOKEN@github.com/pbabbott/home-web-apps
      - git fetch
      - nx affected --target=version --base=refs/tags/last-release --head=origin/main --parallel=false
      - git tag -f last-release
      - git push origin last-release --force

image_pull_secrets:
  - REG_CRED

volumes:
  - name: yarn_cache
    host:
      path: /var/lib/cache/yarn
  - name: node_module_cache
    host:
      path: /var/lib/cache/node_modules

