kind: pipeline
name: release
type: docker
platform:
  os: linux
  arch: arm64
trigger:
  branch:
    - main
  ref:
    exclude:
      - refs/tags/*

steps:
  - name: Semanticially Version packages based on affected changes
    image: registry.nas.local.abbottland.io/drone-node-gh-cli:1.1.0
    volumes:
      - name: cache
        path: /tmp/npm_cache
    environment:
      NPM_REGISTRY_PROTO: https
      NPM_REGISTRY: verdaccio.nas.local.abbottland.io
      NPM_TOKEN:
        from_secret: NPM_TOKEN
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      NX_BASE: origin/main~1
      NX_HEAD: origin/main
    commands:
    - git config user.name "Brandon Abbott"
    - git config user.email "pbabbott@gmail.com"
    - yarn config set cache-folder /tmp/npm_cache
    - yarn --frozen-lockfile
    - nx affected --target version 

image_pull_secrets:
  - REG_CRED

volumes:
  - name: cache
    host:
      path: /var/lib/cache


# tages:
#   - release
# release:
#   rules:
#     - if: $CI_COMMIT_BRANCH == "master"
#       when: manual
#   stage: release
#   image: node:16.13.2
#   before_script:
#     - git config --global user.name "GitLab Bot"
#     - git config --global user.email "gituser@example.com"
#     - git remote set-url origin http://gitlab-ci-token:${DEPLOY_KEY}@gitlab.com/org/project.git
#   script:
#     - yarn install --frozen-lockfile
#     - yarn nx affected --target=version --base=last-release
#     - git tag -f last-release
#     - git push origin last-release --force -o ci.skip