version: v2beta1
name: remote-dev

localRegistry:
  enabled: false

vars:
  DEVSPACE_ENV_FILE: ".env"
  KANIKO: '{ "pullSecret": "regcred", "nodeSelector": { "kubernetes.io/arch": "amd64" } }'

pullSecrets:
  harbor:
    registry: harbor.local.abbottland.io
    secret: regcred

pipelines:
  dev:
    run: |-
      start_dev --all
  deploy: 
    run: |-
      run_dependencies --all
      ensure_pull_secrets --all
      run_pipelines build
      create_deployments --all
  build-base:
    run: |-
      build_images node-18-pnpm-turbo
  build:
    run: |-
      run_dependencies --all --pipeline build
      run_pipelines build-base
      build_images gluetun-sync-builder
      build_images gluetun-sync

images:
  node-18-pnpm-turbo:
    image: harbor.local.abbottland.io/library/node-18-pnpm-turbo
    target: base
    dockerfile: ./docker/medium.Dockerfile
    context: ./docker/
    kaniko: '$(echo $KANIKO)'
    createPullSecret: false
    tags:
      - latest

  gluetun-sync-builder:
    image: harbor.local.abbottland.io/library/gluetun-sync-builder
    dockerfile: ./docker/medium.Dockerfile
    target: builder
    buildArgs:
      PROJECT: "@abbottland/gluetun-sync"
    kaniko: '$(echo $KANIKO)'
    createPullSecret: false
    tags:
      - latest

  gluetun-sync:
    image: harbor.local.abbottland.io/library/gluetun-sync
    dockerfile: ./docker/medium.Dockerfile
    buildArgs:
      PROJECT: "@abbottland/gluetun-sync"
    kaniko: '$(echo $KANIKO)'
    createPullSecret: false
    tags:
      - latest

dev:
  gluetun-sync:
    sync:
      - path: ./apps/gluetun-sync/src:/app/apps/gluetun-sync/src
    logs:
      enabled: true
    labelSelector:
      app: gluetun
    container: gluetun-sync
    namespace: media
    devImage: harbor.local.abbottland.io/library/gluetun-sync-builder
    command: ["turbo"]
    args: ["dev", "--filter=@abbottland/gluetun-sync", "--log-prefix=none", "--env-mode=loose"]
    env:
      - name: GLUETUN_API_HOST
        value: http://localhost:8000
      - name: QBITTORRENT_API_HOST
        value: http://localhost:8080
      - name: QBITTORRENT_USERNAME
        value: admin
      - name: QBITTORRENT_PASSWORD
        value: taMb9W2hP