services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    ports:
      - "8000:8000"
      - "8888:8888"
      - "8388:8388/tcp"
      - "8388:8388/udp"
    environment:
      - TZ=America/Chicago
      - VPN_SERVICE_PROVIDER=private internet access
      - SERVER_REGIONS=CA Toronto
      - PORT_FORWARD_ONLY=true
      - VPN_PORT_FORWARDING=on
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
    env_file:
      - .env
    cap_add:
      - NET_ADMIN

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - "8080:8080"
    environment:
      - QBITTORRENT_USERNAME=admin
      - QBITTORRENT_API_HOST=http://localhost:8080
      - QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD}
    volumes:
    # Default password in this configuration is set to Password123
    - ./docker/conf/qBittorrent/qBittorrent.conf:/config/qBittorrent/qBittorrent.conf
    

# gluetun-sync config
# PORT: "4000"
# GLUETUN_API_HOST: http://localhost:8000
# QBITTORRENT_API_HOST: http://localhost:8080
# QBITTORRENT_USERNAME: admin
# CRON_EXPRESSION: "*/20 * * * *"