packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  typescript: ^5.9.3

  # Express is at v5
  express: ^5.0.3
  '@types/express': '^5.0.3'

  # Node is at 22.X, and @types/node is at 22.X
  # Once I upgrade to Node 24, I can upgrade @types/node to 24.X
  '@types/node': '^22'

  # Jest is at 29.X and ts-jest is at 29.X
  # Waiting for ts-jest to update to 30.X
  jest: '^29.7.0'
  '@types/jest': '^29.5.14'
  ts-jest: '^29.4.4'
  ts-node: '^10.9.2'
