// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('Scrollbar Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('default', async ({ page }) => {
    await gotoStory(page, 'components-scrollbar--default');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-scrollbar--default.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('near-bottom', async ({ page }) => {
    await gotoStory(page, 'components-scrollbar--near-bottom');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-scrollbar--near-bottom.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('large-thumb', async ({ page }) => {
    await gotoStory(page, 'components-scrollbar--large-thumb');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-scrollbar--large-thumb.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('small-thumb', async ({ page }) => {
    await gotoStory(page, 'components-scrollbar--small-thumb');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-scrollbar--small-thumb.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('no-dots', async ({ page }) => {
    await gotoStory(page, 'components-scrollbar--no-dots');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-scrollbar--no-dots.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('interactive', async ({ page }) => {
    await gotoStory(page, 'components-scrollbar--interactive');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-scrollbar--interactive.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('with-content', async ({ page }) => {
    await gotoStory(page, 'components-scrollbar--with-content');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-scrollbar--with-content.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
