import type { FuiIconDefinition } from './types';

export const ICON_REGISTRY: FuiIconDefinition[] = [
  // simple-icons (brand/tech logos)
  {
    id: 'ansible',
    label: 'Ansible',
    slug: 'ansible',
    source: 'simple',
    keywords: ['devops', 'automation', 'iac'],
  },
  {
    id: 'bash',
    label: 'Bash',
    slug: 'gnubash',
    source: 'simple',
    keywords: ['shell', 'scripting', 'terminal'],
  },
  {
    id: 'cloudflare',
    label: 'Cloudflare',
    slug: 'cloudflare',
    source: 'simple',
    keywords: ['cdn', 'dns', 'proxy'],
  },
  {
    id: 'debian',
    label: 'Debian',
    slug: 'debian',
    source: 'simple',
    keywords: ['linux', 'os'],
  },
  {
    id: 'docker',
    label: 'Docker',
    slug: 'docker',
    source: 'simple',
    keywords: ['container', 'devops'],
  },
  {
    id: 'github',
    label: 'GitHub',
    slug: 'github',
    source: 'simple',
    keywords: ['git', 'vcs', 'ci'],
  },
  {
    id: 'grafana',
    label: 'Grafana',
    slug: 'grafana',
    source: 'simple',
    keywords: ['monitoring', 'dashboard', 'observability'],
  },
  {
    id: 'helm',
    label: 'Helm',
    slug: 'helm',
    source: 'simple',
    keywords: ['kubernetes', 'k8s', 'package'],
  },
  {
    id: 'istio',
    label: 'Istio',
    slug: 'istio',
    source: 'simple',
    keywords: ['service-mesh', 'kubernetes'],
  },
  {
    id: 'kubernetes',
    label: 'Kubernetes',
    slug: 'kubernetes',
    source: 'simple',
    keywords: ['k8s', 'container', 'orchestration'],
  },
  {
    id: 'linux',
    label: 'Linux',
    slug: 'linux',
    source: 'simple',
    keywords: ['os', 'kernel'],
  },
  {
    id: 'mongodb',
    label: 'MongoDB',
    slug: 'mongodb',
    source: 'simple',
    keywords: ['database', 'nosql'],
  },
  {
    id: 'mysql',
    label: 'MySQL',
    slug: 'mysql',
    source: 'simple',
    keywords: ['database', 'sql', 'rdbms'],
  },
  {
    id: 'nextjs',
    label: 'Next.js',
    slug: 'nextdotjs',
    source: 'simple',
    keywords: ['react', 'ssr', 'web'],
  },
  {
    id: 'nginx',
    label: 'Nginx',
    slug: 'nginx',
    source: 'simple',
    keywords: ['web-server', 'proxy', 'load-balancer'],
  },
  {
    id: 'n8n',
    label: 'n8n',
    slug: 'n8n',
    source: 'simple',
    keywords: ['automation', 'workflow', 'integration'],
  },
  {
    id: 'nodejs',
    label: 'Node.js',
    slug: 'nodedotjs',
    source: 'simple',
    keywords: ['javascript', 'runtime', 'server'],
  },
  {
    id: 'opentelemetry',
    label: 'OpenTelemetry',
    slug: 'opentelemetry',
    source: 'simple',
    keywords: ['observability', 'tracing', 'metrics'],
  },
  {
    id: 'pnpm',
    label: 'pnpm',
    slug: 'pnpm',
    source: 'simple',
    keywords: ['package-manager', 'node'],
  },
  {
    id: 'postgres',
    label: 'PostgreSQL',
    slug: 'postgresql',
    source: 'simple',
    keywords: ['database', 'sql', 'rdbms'],
  },
  {
    id: 'proxmox',
    label: 'Proxmox',
    slug: 'proxmox',
    source: 'simple',
    keywords: ['virtualization', 'hypervisor', 'homelab'],
  },
  {
    id: 'prometheus',
    label: 'Prometheus',
    slug: 'prometheus',
    source: 'simple',
    keywords: ['monitoring', 'metrics', 'observability'],
  },
  {
    id: 'python',
    label: 'Python',
    slug: 'python',
    source: 'simple',
    keywords: ['language', 'scripting'],
  },
  {
    id: 'rabbitmq',
    label: 'RabbitMQ',
    slug: 'rabbitmq',
    source: 'simple',
    keywords: ['messaging', 'queue', 'amqp'],
  },
  {
    id: 'raspberry-pi',
    label: 'Raspberry Pi',
    slug: 'raspberrypi',
    source: 'simple',
    keywords: ['hardware', 'iot', 'embedded'],
  },
  {
    id: 'react',
    label: 'React',
    slug: 'react',
    source: 'simple',
    keywords: ['ui', 'javascript', 'frontend'],
  },
  {
    id: 'redis',
    label: 'Redis',
    slug: 'redis',
    source: 'simple',
    keywords: ['cache', 'database', 'nosql'],
  },
  {
    id: 'terraform',
    label: 'Terraform',
    slug: 'terraform',
    source: 'simple',
    keywords: ['iac', 'devops', 'hashicorp'],
  },
  {
    id: 'typescript',
    label: 'TypeScript',
    slug: 'typescript',
    source: 'simple',
    keywords: ['language', 'javascript'],
  },
  {
    id: 'ubuntu',
    label: 'Ubuntu',
    slug: 'ubuntu',
    source: 'simple',
    keywords: ['linux', 'os', 'debian'],
  },

  // custom icons (not in simple-icons)
  {
    id: 'banana',
    label: 'Banana',
    slug: 'banana',
    source: 'custom',
    keywords: ['fruit', 'yellow'],
  },
  {
    id: 'haproxy',
    label: 'HAProxy',
    slug: 'haproxy',
    source: 'custom',
    keywords: ['load-balancer', 'proxy'],
  },
  {
    id: 'router',
    label: 'Router',
    slug: 'router',
    source: 'custom',
    keywords: ['network', 'wifi', 'gateway'],
  },

  // radix icons (generic symbols for diagrams)
  {
    id: 'radix-globe',
    label: 'Globe',
    slug: 'GlobeIcon',
    source: 'radix',
    keywords: ['web', 'internet', 'network', 'world'],
  },
  {
    id: 'radix-home',
    label: 'Home',
    slug: 'HomeIcon',
    source: 'radix',
    keywords: ['house', 'home', 'local', 'origin'],
  },
  {
    id: 'radix-desktop',
    label: 'Desktop',
    slug: 'DesktopIcon',
    source: 'radix',
    keywords: ['computer', 'server', 'machine', 'host'],
  },
  {
    id: 'radix-mobile',
    label: 'Mobile',
    slug: 'MobileIcon',
    source: 'radix',
    keywords: ['phone', 'device', 'client'],
  },
  {
    id: 'radix-cube',
    label: 'Cube',
    slug: 'CubeIcon',
    source: 'radix',
    keywords: ['package', 'module', 'service', '3d'],
  },
  {
    id: 'radix-box',
    label: 'Box',
    slug: 'BoxIcon',
    source: 'radix',
    keywords: ['package', 'container', 'module'],
  },
  {
    id: 'radix-container',
    label: 'Container',
    slug: 'ContainerIcon',
    source: 'radix',
    keywords: ['docker', 'pod', 'box'],
  },
  {
    id: 'radix-stack',
    label: 'Stack',
    slug: 'StackIcon',
    source: 'radix',
    keywords: ['layers', 'tier', 'backend'],
  },
  {
    id: 'radix-layers',
    label: 'Layers',
    slug: 'LayersIcon',
    source: 'radix',
    keywords: ['stack', 'tier', 'architecture'],
  },
  {
    id: 'radix-gear',
    label: 'Gear',
    slug: 'GearIcon',
    source: 'radix',
    keywords: ['settings', 'config', 'service'],
  },
  {
    id: 'radix-lock-closed',
    label: 'Lock',
    slug: 'LockClosedIcon',
    source: 'radix',
    keywords: ['security', 'auth', 'tls', 'ssl'],
  },
  {
    id: 'radix-lock-open',
    label: 'Unlock',
    slug: 'LockOpen1Icon',
    source: 'radix',
    keywords: ['security', 'open', 'auth'],
  },
  {
    id: 'radix-key',
    label: 'Key',
    slug: 'KeyboardIcon',
    source: 'radix',
    keywords: ['auth', 'secret', 'credential'],
  },
  {
    id: 'radix-code',
    label: 'Code',
    slug: 'CodeIcon',
    source: 'radix',
    keywords: ['app', 'service', 'function', 'lambda'],
  },
  {
    id: 'radix-file',
    label: 'File',
    slug: 'FileIcon',
    source: 'radix',
    keywords: ['document', 'storage', 'config'],
  },
  {
    id: 'radix-file-text',
    label: 'File Text',
    slug: 'FileTextIcon',
    source: 'radix',
    keywords: ['document', 'log', 'config'],
  },
  {
    id: 'radix-archive',
    label: 'Archive',
    slug: 'ArchiveIcon',
    source: 'radix',
    keywords: ['storage', 'backup', 'artifact'],
  },
  {
    id: 'radix-share',
    label: 'Share',
    slug: 'Share1Icon',
    source: 'radix',
    keywords: ['network', 'distribute', 'broadcast'],
  },
  {
    id: 'radix-link',
    label: 'Link',
    slug: 'Link1Icon',
    source: 'radix',
    keywords: ['connection', 'url', 'reference'],
  },
  {
    id: 'radix-person',
    label: 'Person',
    slug: 'PersonIcon',
    source: 'radix',
    keywords: ['user', 'account', 'actor', 'client'],
  },
  {
    id: 'radix-lightning',
    label: 'Lightning',
    slug: 'LightningBoltIcon',
    source: 'radix',
    keywords: ['fast', 'event', 'trigger', 'power'],
  },
  {
    id: 'radix-card-stack',
    label: 'Card Stack',
    slug: 'CardStackIcon',
    source: 'radix',
    keywords: ['queue', 'batch', 'collection', 'data'],
  },
  {
    id: 'radix-mixer',
    label: 'Mixer',
    slug: 'MixerVerticalIcon',
    source: 'radix',
    keywords: ['config', 'tune', 'settings'],
  },
  {
    id: 'radix-component',
    label: 'Component',
    slug: 'Component1Icon',
    source: 'radix',
    keywords: ['module', 'plugin', 'widget'],
  },
  {
    id: 'radix-circle',
    label: 'Circle',
    slug: 'CircleIcon',
    source: 'radix',
    keywords: ['node', 'endpoint', 'generic'],
  },
  {
    id: 'radix-dot',
    label: 'Dot',
    slug: 'DotFilledIcon',
    source: 'radix',
    keywords: ['node', 'point', 'status'],
  },
];

export function lookupById(id: string): FuiIconDefinition | undefined {
  return ICON_REGISTRY.find((icon) => icon.id === id);
}
