import type { FuiIconDefinition } from './types';

export const ICON_REGISTRY: FuiIconDefinition[] = [
  {
    id: 'ansible',
    label: 'Ansible',
    slug: 'ansible',
    keywords: ['devops', 'automation', 'iac'],
  },
  {
    id: 'apachekafka',
    label: 'Apache Kafka',
    slug: 'apachekafka',
    keywords: ['messaging', 'streaming', 'queue'],
  },
  { id: 'aws', label: 'AWS', slug: 'amazonaws', keywords: ['cloud', 'amazon'] },
  {
    id: 'azure',
    label: 'Azure',
    slug: 'microsoftazure',
    keywords: ['cloud', 'microsoft'],
  },
  {
    id: 'bash',
    label: 'Bash',
    slug: 'gnubash',
    keywords: ['shell', 'scripting', 'terminal'],
  },
  {
    id: 'caddy',
    label: 'Caddy',
    slug: 'caddy',
    keywords: ['server', 'proxy', 'web'],
  },
  {
    id: 'cassandra',
    label: 'Cassandra',
    slug: 'apachecassandra',
    keywords: ['database', 'nosql'],
  },
  {
    id: 'cloudflare',
    label: 'Cloudflare',
    slug: 'cloudflare',
    keywords: ['cdn', 'dns', 'proxy'],
  },
  {
    id: 'consul',
    label: 'Consul',
    slug: 'consul',
    keywords: ['service-mesh', 'discovery', 'hashicorp'],
  },
  { id: 'debian', label: 'Debian', slug: 'debian', keywords: ['linux', 'os'] },
  {
    id: 'docker',
    label: 'Docker',
    slug: 'docker',
    keywords: ['container', 'devops'],
  },
  {
    id: 'elasticsearch',
    label: 'Elasticsearch',
    slug: 'elasticsearch',
    keywords: ['search', 'database', 'elk'],
  },
  {
    id: 'envoy',
    label: 'Envoy',
    slug: 'envoyproxy',
    keywords: ['proxy', 'service-mesh'],
  },
  {
    id: 'fastapi',
    label: 'FastAPI',
    slug: 'fastapi',
    keywords: ['api', 'python', 'web'],
  },
  {
    id: 'flutter',
    label: 'Flutter',
    slug: 'flutter',
    keywords: ['mobile', 'dart', 'ui'],
  },
  {
    id: 'gcp',
    label: 'Google Cloud',
    slug: 'googlecloud',
    keywords: ['cloud', 'google', 'gcp'],
  },
  {
    id: 'github',
    label: 'GitHub',
    slug: 'github',
    keywords: ['git', 'vcs', 'ci'],
  },
  {
    id: 'gitlab',
    label: 'GitLab',
    slug: 'gitlab',
    keywords: ['git', 'vcs', 'ci'],
  },
  { id: 'go', label: 'Go', slug: 'go', keywords: ['golang', 'language'] },
  {
    id: 'grafana',
    label: 'Grafana',
    slug: 'grafana',
    keywords: ['monitoring', 'dashboard', 'observability'],
  },
  {
    id: 'grpc',
    label: 'gRPC',
    slug: 'grpc',
    keywords: ['rpc', 'api', 'protobuf'],
  },
  {
    id: 'haproxy',
    label: 'HAProxy',
    slug: 'haproxy',
    keywords: ['load-balancer', 'proxy'],
  },
  {
    id: 'helm',
    label: 'Helm',
    slug: 'helm',
    keywords: ['kubernetes', 'k8s', 'package'],
  },
  {
    id: 'istio',
    label: 'Istio',
    slug: 'istio',
    keywords: ['service-mesh', 'kubernetes'],
  },
  {
    id: 'jenkins',
    label: 'Jenkins',
    slug: 'jenkins',
    keywords: ['ci', 'cd', 'pipeline'],
  },
  {
    id: 'kafka',
    label: 'Kafka',
    slug: 'apachekafka',
    keywords: ['messaging', 'streaming'],
  },
  {
    id: 'kibana',
    label: 'Kibana',
    slug: 'kibana',
    keywords: ['elk', 'logging', 'dashboard'],
  },
  {
    id: 'kotlin',
    label: 'Kotlin',
    slug: 'kotlin',
    keywords: ['language', 'jvm', 'android'],
  },
  {
    id: 'kubernetes',
    label: 'Kubernetes',
    slug: 'kubernetes',
    keywords: ['k8s', 'container', 'orchestration'],
  },
  { id: 'linux', label: 'Linux', slug: 'linux', keywords: ['os', 'kernel'] },
  {
    id: 'loki',
    label: 'Loki',
    slug: 'grafanaloki',
    keywords: ['logging', 'monitoring', 'observability'],
  },
  {
    id: 'mongodb',
    label: 'MongoDB',
    slug: 'mongodb',
    keywords: ['database', 'nosql'],
  },
  {
    id: 'mysql',
    label: 'MySQL',
    slug: 'mysql',
    keywords: ['database', 'sql', 'rdbms'],
  },
  {
    id: 'nestjs',
    label: 'NestJS',
    slug: 'nestjs',
    keywords: ['node', 'api', 'typescript'],
  },
  {
    id: 'nextjs',
    label: 'Next.js',
    slug: 'nextdotjs',
    keywords: ['react', 'ssr', 'web'],
  },
  {
    id: 'nginx',
    label: 'Nginx',
    slug: 'nginx',
    keywords: ['web-server', 'proxy', 'load-balancer'],
  },
  {
    id: 'nodejs',
    label: 'Node.js',
    slug: 'nodedotjs',
    keywords: ['javascript', 'runtime', 'server'],
  },
  {
    id: 'opentelemetry',
    label: 'OpenTelemetry',
    slug: 'opentelemetry',
    keywords: ['observability', 'tracing', 'metrics'],
  },
  {
    id: 'pnpm',
    label: 'pnpm',
    slug: 'pnpm',
    keywords: ['package-manager', 'node'],
  },
  {
    id: 'postgres',
    label: 'PostgreSQL',
    slug: 'postgresql',
    keywords: ['database', 'sql', 'rdbms'],
  },
  {
    id: 'prometheus',
    label: 'Prometheus',
    slug: 'prometheus',
    keywords: ['monitoring', 'metrics', 'observability'],
  },
  {
    id: 'python',
    label: 'Python',
    slug: 'python',
    keywords: ['language', 'scripting'],
  },
  {
    id: 'rabbitmq',
    label: 'RabbitMQ',
    slug: 'rabbitmq',
    keywords: ['messaging', 'queue', 'amqp'],
  },
  {
    id: 'raspberry-pi',
    label: 'Raspberry Pi',
    slug: 'raspberrypi',
    keywords: ['hardware', 'iot', 'embedded'],
  },
  {
    id: 'react',
    label: 'React',
    slug: 'react',
    keywords: ['ui', 'javascript', 'frontend'],
  },
  {
    id: 'redis',
    label: 'Redis',
    slug: 'redis',
    keywords: ['cache', 'database', 'nosql'],
  },
  {
    id: 'rust',
    label: 'Rust',
    slug: 'rust',
    keywords: ['language', 'systems'],
  },
  {
    id: 'terraform',
    label: 'Terraform',
    slug: 'terraform',
    keywords: ['iac', 'devops', 'hashicorp'],
  },
  {
    id: 'typescript',
    label: 'TypeScript',
    slug: 'typescript',
    keywords: ['language', 'javascript'],
  },
  {
    id: 'ubuntu',
    label: 'Ubuntu',
    slug: 'ubuntu',
    keywords: ['linux', 'os', 'debian'],
  },
  {
    id: 'vault',
    label: 'Vault',
    slug: 'vault',
    keywords: ['secrets', 'security', 'hashicorp'],
  },
];

export function lookupById(id: string): FuiIconDefinition | undefined {
  return ICON_REGISTRY.find((icon) => icon.id === id);
}
