// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import { gotoStory, STANDARD_VIEWPORT, SCREENSHOT_OPTIONS } from '../../../tests/playwright-helpers';

test.describe('Button Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });


  test('color-primary', async ({ page }) => {
    await gotoStory(page, 'components-button--color-primary');
    await expect(page).toHaveScreenshot('components-button--color-primary.png', SCREENSHOT_OPTIONS);
  });


  test('color-secondary', async ({ page }) => {
    await gotoStory(page, 'components-button--color-secondary');
    await expect(page).toHaveScreenshot('components-button--color-secondary.png', SCREENSHOT_OPTIONS);
  });


  test('color-success', async ({ page }) => {
    await gotoStory(page, 'components-button--color-success');
    await expect(page).toHaveScreenshot('components-button--color-success.png', SCREENSHOT_OPTIONS);
  });


  test('color-error', async ({ page }) => {
    await gotoStory(page, 'components-button--color-error');
    await expect(page).toHaveScreenshot('components-button--color-error.png', SCREENSHOT_OPTIONS);
  });


  test('color-warning', async ({ page }) => {
    await gotoStory(page, 'components-button--color-warning');
    await expect(page).toHaveScreenshot('components-button--color-warning.png', SCREENSHOT_OPTIONS);
  });


  test('color-accent-purple', async ({ page }) => {
    await gotoStory(page, 'components-button--color-accent-purple');
    await expect(page).toHaveScreenshot('components-button--color-accent-purple.png', SCREENSHOT_OPTIONS);
  });


  test('color-accent-falcon', async ({ page }) => {
    await gotoStory(page, 'components-button--color-accent-falcon');
    await expect(page).toHaveScreenshot('components-button--color-accent-falcon.png', SCREENSHOT_OPTIONS);
  });


  test('variant-contained', async ({ page }) => {
    await gotoStory(page, 'components-button--variant-contained');
    await expect(page).toHaveScreenshot('components-button--variant-contained.png', SCREENSHOT_OPTIONS);
  });


  test('variant-outlined', async ({ page }) => {
    await gotoStory(page, 'components-button--variant-outlined');
    await expect(page).toHaveScreenshot('components-button--variant-outlined.png', SCREENSHOT_OPTIONS);
  });


  test('variant-text', async ({ page }) => {
    await gotoStory(page, 'components-button--variant-text');
    await expect(page).toHaveScreenshot('components-button--variant-text.png', SCREENSHOT_OPTIONS);
  });


});

