// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('DotGridBackground Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('default', async ({ page }) => {
    await gotoStory(page, 'components-dotgridbackground--default');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-dotgridbackground--default.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('active', async ({ page }) => {
    await gotoStory(page, 'components-dotgridbackground--active');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-dotgridbackground--active.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('primary', async ({ page }) => {
    await gotoStory(page, 'components-dotgridbackground--primary');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-dotgridbackground--primary.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('primary-active', async ({ page }) => {
    await gotoStory(page, 'components-dotgridbackground--primary-active');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-dotgridbackground--primary-active.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
