// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('TypographyShowcase Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('variants', async ({ page }) => {
    await gotoStory(page, 'showcase-typography--variants');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'showcase-typography--variants.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('blog', async ({ page }) => {
    await gotoStory(page, 'showcase-typography--blog');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'showcase-typography--blog.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('blog-mobile', async ({ page }) => {
    await gotoStory(page, 'showcase-typography--blog-mobile');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'showcase-typography--blog-mobile.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
