// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('HexagonButton Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('default', async ({ page }) => {
    await gotoStory(page, 'components-hexagonbutton--default');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-hexagonbutton--default.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('with-label', async ({ page }) => {
    await gotoStory(page, 'components-hexagonbutton--with-label');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-hexagonbutton--with-label.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('with-label-and-lower-label', async ({ page }) => {
    await gotoStory(
      page,
      'components-hexagonbutton--with-label-and-lower-label',
    );
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-hexagonbutton--with-label-and-lower-label.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('long-label', async ({ page }) => {
    await gotoStory(page, 'components-hexagonbutton--long-label');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-hexagonbutton--long-label.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('wrapping-long-word', async ({ page }) => {
    await gotoStory(page, 'components-hexagonbutton--wrapping-long-word');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-hexagonbutton--wrapping-long-word.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('active', async ({ page }) => {
    await gotoStory(page, 'components-hexagonbutton--active');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-hexagonbutton--active.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
