// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('Switch Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('off', async ({ page }) => {
    await gotoStory(page, 'components-switch--off');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-switch--off.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('on', async ({ page }) => {
    await gotoStory(page, 'components-switch--on');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-switch--on.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('disabled', async ({ page }) => {
    await gotoStory(page, 'components-switch--disabled');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-switch--disabled.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('disabled-on', async ({ page }) => {
    await gotoStory(page, 'components-switch--disabled-on');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-switch--disabled-on.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
