// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('TransparentPanel Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('default', async ({ page }) => {
    await gotoStory(page, 'components-transparentpanel--default');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-transparentpanel--default.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('dark', async ({ page }) => {
    await gotoStory(page, 'components-transparentpanel--dark');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-transparentpanel--dark.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('white', async ({ page }) => {
    await gotoStory(page, 'components-transparentpanel--white');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-transparentpanel--white.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('primary', async ({ page }) => {
    await gotoStory(page, 'components-transparentpanel--primary');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-transparentpanel--primary.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('secondary', async ({ page }) => {
    await gotoStory(page, 'components-transparentpanel--secondary');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-transparentpanel--secondary.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('success', async ({ page }) => {
    await gotoStory(page, 'components-transparentpanel--success');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-transparentpanel--success.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('error', async ({ page }) => {
    await gotoStory(page, 'components-transparentpanel--error');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-transparentpanel--error.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('warning', async ({ page }) => {
    await gotoStory(page, 'components-transparentpanel--warning');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-transparentpanel--warning.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('accent-purple', async ({ page }) => {
    await gotoStory(page, 'components-transparentpanel--accent-purple');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-transparentpanel--accent-purple.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('accent-falcon', async ({ page }) => {
    await gotoStory(page, 'components-transparentpanel--accent-falcon');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-transparentpanel--accent-falcon.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
