// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('DotGridBackgroundShowcase Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('all-colors', async ({ page }) => {
    await gotoStory(page, 'showcase-dotgridbackground--all-colors');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'showcase-dotgridbackground--all-colors.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('active', async ({ page }) => {
    await gotoStory(page, 'showcase-dotgridbackground--active');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'showcase-dotgridbackground--active.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
