// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import { gotoStory, STANDARD_VIEWPORT, SCREENSHOT_OPTIONS } from '../../../tests/playwright-helpers';

test.describe('Input Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });


  test('default', async ({ page }) => {
    await gotoStory(page, 'components-input--default');
    await expect(page).toHaveScreenshot('components-input--default.png', SCREENSHOT_OPTIONS);
  });


  test('primary', async ({ page }) => {
    await gotoStory(page, 'components-input--primary');
    await expect(page).toHaveScreenshot('components-input--primary.png', SCREENSHOT_OPTIONS);
  });


});

