// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import { gotoStory, STANDARD_VIEWPORT, SCREENSHOT_OPTIONS } from '../../../tests/playwright-helpers';

test.describe('PanelShowcase Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });


  test('all-colors', async ({ page }) => {
    await gotoStory(page, 'showcase-panel--all-colors');
    await expect(page).toHaveScreenshot('showcase-panel--all-colors.png', SCREENSHOT_OPTIONS);
  });


});

