// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('AIContent Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('unhighlighted', async ({ page }) => {
    await gotoStory(page, 'components-aicontent--unhighlighted');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-aicontent--unhighlighted.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('highlighted-animated', async ({ page }) => {
    await gotoStory(page, 'components-aicontent--highlighted-animated');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-aicontent--highlighted-animated.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('highlighted-static', async ({ page }) => {
    await gotoStory(page, 'components-aicontent--highlighted-static');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-aicontent--highlighted-static.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
