// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('TextNode Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('default', async ({ page }) => {
    await gotoStory(page, 'diagrams-textnode--default');
    await expect(page).toHaveScreenshot(
      'diagrams-textnode--default.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('primary', async ({ page }) => {
    await gotoStory(page, 'diagrams-textnode--primary');
    await expect(page).toHaveScreenshot(
      'diagrams-textnode--primary.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('secondary', async ({ page }) => {
    await gotoStory(page, 'diagrams-textnode--secondary');
    await expect(page).toHaveScreenshot(
      'diagrams-textnode--secondary.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('selected', async ({ page }) => {
    await gotoStory(page, 'diagrams-textnode--selected');
    await expect(page).toHaveScreenshot(
      'diagrams-textnode--selected.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('readonly', async ({ page }) => {
    await gotoStory(page, 'diagrams-textnode--readonly');
    await expect(page).toHaveScreenshot(
      'diagrams-textnode--readonly.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('multiline', async ({ page }) => {
    await gotoStory(page, 'diagrams-textnode--multiline');
    await expect(page).toHaveScreenshot(
      'diagrams-textnode--multiline.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
