// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('BaseNode Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('default', async ({ page }) => {
    await gotoStory(page, 'diagrams-basenode--default');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'diagrams-basenode--default.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('with-label', async ({ page }) => {
    await gotoStory(page, 'diagrams-basenode--with-label');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'diagrams-basenode--with-label.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('primary', async ({ page }) => {
    await gotoStory(page, 'diagrams-basenode--primary');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'diagrams-basenode--primary.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('secondary', async ({ page }) => {
    await gotoStory(page, 'diagrams-basenode--secondary');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'diagrams-basenode--secondary.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('selected', async ({ page }) => {
    await gotoStory(page, 'diagrams-basenode--selected');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'diagrams-basenode--selected.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('with-handles', async ({ page }) => {
    await gotoStory(page, 'diagrams-basenode--with-handles');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'diagrams-basenode--with-handles.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('labeled-with-handles', async ({ page }) => {
    await gotoStory(page, 'diagrams-basenode--labeled-with-handles');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'diagrams-basenode--labeled-with-handles.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('custom-size', async ({ page }) => {
    await gotoStory(page, 'diagrams-basenode--custom-size');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'diagrams-basenode--custom-size.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('multiline-content', async ({ page }) => {
    await gotoStory(page, 'diagrams-basenode--multiline-content');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'diagrams-basenode--multiline-content.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('default-with-icon', async ({ page }) => {
    await gotoStory(page, 'diagrams-basenode--default-with-icon');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'diagrams-basenode--default-with-icon.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('labeled-with-icon', async ({ page }) => {
    await gotoStory(page, 'diagrams-basenode--labeled-with-icon');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'diagrams-basenode--labeled-with-icon.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
