// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('DropdownMenu Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('default', async ({ page }) => {
    await gotoStory(page, 'components-dropdownmenu--default');
    await expect(page).toHaveScreenshot(
      'components-dropdownmenu--default.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('open', async ({ page }) => {
    await gotoStory(page, 'components-dropdownmenu--open');
    await expect(page).toHaveScreenshot(
      'components-dropdownmenu--open.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
