FROM node:16

RUN apt-get update \
	&& apt-get install -y \
	curl \
	git \
	golang \
	sudo \
	vim \
	wget \
	jq \
	zsh \
	neofetch \
	&& rm -rf /var/lib/apt/lists/*

ARG USER=coder
RUN useradd --groups sudo --no-create-home --shell /usr/bin/zsh ${USER} \
	&& echo "${USER} ALL=(ALL) NOPASSWD:ALL" >/etc/sudoers.d/${USER} \
	&& chmod 0440 /etc/sudoers.d/${USER}

RUN mkdir -p /home/${USER} \
	&& chown -R ${USER} /home/${USER}

USER ${USER}
WORKDIR /home/${USER}
COPY .zshrc /home/${USER}/.zshrc

