// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('Table Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('default', async ({ page }) => {
    await gotoStory(page, 'components-table--default');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-table--default.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('multi-column', async ({ page }) => {
    await gotoStory(page, 'components-table--multi-column');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-table--multi-column.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('wide-table', async ({ page }) => {
    await gotoStory(page, 'components-table--wide-table');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-table--wide-table.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('secondary', async ({ page }) => {
    await gotoStory(page, 'components-table--secondary');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-table--secondary.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
