// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('NavItem Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('default', async ({ page }) => {
    await gotoStory(page, 'components-navitem--default');
    await expect(page).toHaveScreenshot(
      'components-navitem--default.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('active', async ({ page }) => {
    await gotoStory(page, 'components-navitem--active');
    await expect(page).toHaveScreenshot(
      'components-navitem--active.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('without-lines', async ({ page }) => {
    await gotoStory(page, 'components-navitem--without-lines');
    await expect(page).toHaveScreenshot(
      'components-navitem--without-lines.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
