// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('HorizontalRule Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('default', async ({ page }) => {
    await gotoStory(page, 'components-horizontalrule--default');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-horizontalrule--default.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('primary', async ({ page }) => {
    await gotoStory(page, 'components-horizontalrule--primary');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-horizontalrule--primary.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('secondary', async ({ page }) => {
    await gotoStory(page, 'components-horizontalrule--secondary');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-horizontalrule--secondary.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('custom-spacing', async ({ page }) => {
    await gotoStory(page, 'components-horizontalrule--custom-spacing');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-horizontalrule--custom-spacing.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
