export enum TerminalEvent {
  WELCOMING_USER = 'WELCOMING_USER',
  INITIALIZING_WEBSITE_TITLE = 'INITIALIZING_WEBSITE_TITLE',
  RENDERING_BACKGROUND_EXPERIENCE = 'RENDERING_BACKGROUND_EXPERIENCE',
  AWAITING_USER_ACTION = 'AWAITING_USER_ACTION',
  STILL_WAITING_FOR_USER_ACTION = 'STILL_WAITING_FOR_USER_ACTION',
  PROCESS_DELAYED = 'PROCESS_DELAYED',
  CLICK_BUTTON_TO_CONTINUE = 'CLICK_BUTTON_TO_CONTINUE',
  SCROLL_DOWN_PAGE = 'SCROLL_DOWN_PAGE',
}
