export enum TerminalEvent {
  WELCOMING_USER = 'WELCOMING_USER',
  INITIALIZING_BACKGROUND_COLORS = 'INITIALIZING_BACKGROUND_COLORS',
  RENDERING_INTERACTIVE_BACKGROUND_EXPERIENCE = 'RENDERING_INTERACTIVE_BACKGROUND_EXPERIENCE',
  AWAITING_USER_ACTION = 'AWAITING_USER_ACTION',
  PROCESS_DELAYED = 'PROCESS_DELAYED',
  CLICK_BUTTON_TO_CONTINUE = 'CLICK_BUTTON_TO_CONTINUE',
}
