// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('DiagramViewerShowcase Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('local-network', async ({ page }) => {
    await gotoStory(page, 'showcase-diagramviewer--local-network');
    await expect(page).toHaveScreenshot(
      'showcase-diagramviewer--local-network.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('with-port-forwarding', async ({ page }) => {
    await gotoStory(page, 'showcase-diagramviewer--with-port-forwarding');
    await expect(page).toHaveScreenshot(
      'showcase-diagramviewer--with-port-forwarding.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('full-network-with-duck-dns', async ({ page }) => {
    await gotoStory(page, 'showcase-diagramviewer--full-network-with-duck-dns');
    await expect(page).toHaveScreenshot(
      'showcase-diagramviewer--full-network-with-duck-dns.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
