// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('HexagonalBackground Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('default', async ({ page }) => {
    await gotoStory(page, 'components-hexagonalbackground--default');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-hexagonalbackground--default.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('sparks-disabled', async ({ page }) => {
    await gotoStory(page, 'components-hexagonalbackground--sparks-disabled');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-hexagonalbackground--sparks-disabled.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('sparks-frozen', async ({ page }) => {
    await gotoStory(page, 'components-hexagonalbackground--sparks-frozen');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-hexagonalbackground--sparks-frozen.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('ice-theme', async ({ page }) => {
    await gotoStory(page, 'components-hexagonalbackground--ice-theme');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-hexagonalbackground--ice-theme.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('error-theme', async ({ page }) => {
    await gotoStory(page, 'components-hexagonalbackground--error-theme');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-hexagonalbackground--error-theme.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
