// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('SegmentedProgressBar Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('index-before-segment', async ({ page }) => {
    await gotoStory(
      page,
      'components-segmentedprogressbar--index-before-segment',
    );
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-segmentedprogressbar--index-before-segment.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('index-at-segment', async ({ page }) => {
    await gotoStory(page, 'components-segmentedprogressbar--index-at-segment');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-segmentedprogressbar--index-at-segment.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('index-after-segment', async ({ page }) => {
    await gotoStory(
      page,
      'components-segmentedprogressbar--index-after-segment',
    );
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-segmentedprogressbar--index-after-segment.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('with-label', async ({ page }) => {
    await gotoStory(page, 'components-segmentedprogressbar--with-label');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-segmentedprogressbar--with-label.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('with-index', async ({ page }) => {
    await gotoStory(page, 'components-segmentedprogressbar--with-index');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-segmentedprogressbar--with-index.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('default', async ({ page }) => {
    await gotoStory(page, 'components-segmentedprogressbar--default');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-segmentedprogressbar--default.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
