// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import { gotoStory, STANDARD_VIEWPORT, SCREENSHOT_OPTIONS } from '../../../tests/playwright-helpers';

test.describe('CardShowcase Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });


  test('all-colors', async ({ page }) => {
    await gotoStory(page, 'showcase-card--all-colors');
    await expect(page).toHaveScreenshot('showcase-card--all-colors.png', SCREENSHOT_OPTIONS);
  });


  test('blog-post', async ({ page }) => {
    await gotoStory(page, 'showcase-card--blog-post');
    await expect(page).toHaveScreenshot('showcase-card--blog-post.png', SCREENSHOT_OPTIONS);
  });


});

