// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('EditableEdge Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('default', async ({ page }) => {
    await gotoStory(page, 'diagrams-editableedge--default');
    await expect(page).toHaveScreenshot(
      'diagrams-editableedge--default.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('new-edge', async ({ page }) => {
    await gotoStory(page, 'diagrams-editableedge--new-edge');
    await expect(page).toHaveScreenshot(
      'diagrams-editableedge--new-edge.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('new-edge-primary-color', async ({ page }) => {
    await gotoStory(page, 'diagrams-editableedge--new-edge-primary-color');
    await expect(page).toHaveScreenshot(
      'diagrams-editableedge--new-edge-primary-color.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('editing', async ({ page }) => {
    await gotoStory(page, 'diagrams-editableedge--editing');
    await expect(page).toHaveScreenshot(
      'diagrams-editableedge--editing.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('default-color', async ({ page }) => {
    await gotoStory(page, 'diagrams-editableedge--default-color');
    await expect(page).toHaveScreenshot(
      'diagrams-editableedge--default-color.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('with-label', async ({ page }) => {
    await gotoStory(page, 'diagrams-editableedge--with-label');
    await expect(page).toHaveScreenshot(
      'diagrams-editableedge--with-label.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('long-label', async ({ page }) => {
    await gotoStory(page, 'diagrams-editableedge--long-label');
    await expect(page).toHaveScreenshot(
      'diagrams-editableedge--long-label.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('multi-line-label', async ({ page }) => {
    await gotoStory(page, 'diagrams-editableedge--multi-line-label');
    await expect(page).toHaveScreenshot(
      'diagrams-editableedge--multi-line-label.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('primary-color', async ({ page }) => {
    await gotoStory(page, 'diagrams-editableedge--primary-color');
    await expect(page).toHaveScreenshot(
      'diagrams-editableedge--primary-color.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('secondary-color', async ({ page }) => {
    await gotoStory(page, 'diagrams-editableedge--secondary-color');
    await expect(page).toHaveScreenshot(
      'diagrams-editableedge--secondary-color.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('multiple-edges', async ({ page }) => {
    await gotoStory(page, 'diagrams-editableedge--multiple-edges');
    await expect(page).toHaveScreenshot(
      'diagrams-editableedge--multiple-edges.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
