name: 'Setup Test Environment'
description: 'Common setup for integration and e2e tests'
inputs:
  op-connect-host:
    description: '1Password Connect host'
    required: true
  op-connect-token:
    description: '1Password Connect token'
    required: true
runs:
  using: composite
  steps:
    - name: Install 1Password CLI
      uses: 1password/install-cli-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      run: pnpm build
      shell: bash

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Build environment files
      run: pnpm env:generate
      shell: bash
      env:
        OP_CONNECT_HOST: ${{ inputs.op-connect-host }}
        OP_CONNECT_TOKEN: ${{ inputs.op-connect-token }}
