name: 'Setup Test Environment'
description: 'Common setup for integration and e2e tests'
runs:
  using: composite
  steps:
    - name: Install 1Password CLI
      uses: 1password/install-cli-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: pnpm install composite action
      uses: ./.github/actions/pnpm-install

    - name: Build
      run: pnpm build:abctl
      shell: bash

    - name: Install dependencies
      run: pnpm install
      shell: bash

    - name: Build environment files
      run: pnpm env:generate
      shell: bash
      env:
        OP_CONNECT_HOST: https://op-connect.local.abbottland.io
        OP_CONNECT_TOKEN: ${{ env.OP_CONNECT_TOKEN }}
