// Auto-generated file - DO NOT EDIT
// Generated by: pnpm test:playwright:generate
import { test, expect } from '@playwright/test';
import {
  gotoStory,
  STANDARD_VIEWPORT,
  SCREENSHOT_OPTIONS,
} from '../../../tests/playwright-helpers';

test.describe('TiledHexagons Visual Regression Tests', () => {
  test.beforeEach(async ({ page }) => {
    await page.setViewportSize(STANDARD_VIEWPORT);
  });

  test('default', async ({ page }) => {
    await gotoStory(page, 'components-tiledhexagons--default');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-tiledhexagons--default.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('custom-grid', async ({ page }) => {
    await gotoStory(page, 'components-tiledhexagons--custom-grid');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-tiledhexagons--custom-grid.png',
      SCREENSHOT_OPTIONS,
    );
  });

  test('custom-gap-three-columns', async ({ page }) => {
    await gotoStory(page, 'components-tiledhexagons--custom-gap-three-columns');
    await expect(page.locator('#storybook-root')).toHaveScreenshot(
      'components-tiledhexagons--custom-gap-three-columns.png',
      SCREENSHOT_OPTIONS,
    );
  });
});
