name: build packages
on: workflow_dispatch
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: pnpm install
        uses: ./.github/actions/pnpm-install
      - name: Build packages
        run: pnpm build