name: Typescript Build
on:
  workflow_dispatch: {}
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/reusable-pnpm-script.yml
    with:
      pnpm-script: build

    # runs-on: [self-hosted, amd64-runner]
    # steps:
    #   - name: Checkout Repo
    #     uses: actions/checkout@v4
    #   - name: pnpm install
    #     uses: ./.github/actions/pnpm-install
    #   - name: Build packages
    #     run: pnpm build
