name: build packages
on: workflow_dispatch
jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9
