name: Typescript Build
on:
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
jobs:
  build:
    runs-on: [self-hosted, amd64-runner]
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: ./.github/actions/pnpm-setup

      - name: Install and build
        uses: ./.github/actions/install-and-build
