name: Typescript Build
on:
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
jobs:
  build:
    runs-on: [prod-gen2-amd64-runner]
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: ./.github/actions/pnpm-setup

      - name: Install and build
        uses: ./.github/actions/install-and-build

  docker-build:
    runs-on: [prod-gen2-dind-runner]
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: ./.github/actions/pnpm-setup

      - name: Install and build
        uses: ./.github/actions/install-and-build

      - name: Install jq
        uses: dcarbone/install-jq-action@v3.2.0

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Docker Login
        run: bash ./scripts/docker-login.sh
        env:
          OP_CONNECT_HOST: https://op-connect.local.abbottland.io
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN_PROD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: pnpm docker:build
        shell: bash
