name: lint packages
on: 
  workflow_dispatch: {}
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
jobs:
  lint:
    uses: ./.github/workflows/reusable-pnpm-script.yml
    with:
      pnpm-script: lint