name: lint packages
on:
  workflow_dispatch: {}
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
jobs:
  lint:
    uses: ./.github/workflows/reusable-pnpm-script.yml
    with:
      pnpm-script: lint
  format:
    uses: ./.github/workflows/reusable-pnpm-script.yml
    with:
      pnpm-script: format:check
