name: Lint Codebase
on:
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  lint:
    runs-on: [self-hosted, amd64-runner]
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: ./.github/actions/pnpm-setup

      - name: Install dependencies
        run: pnpm install

      - name: Run PNPM Script
        run: pnpm lint

  format:
    runs-on: [self-hosted, amd64-runner]
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: ./.github/actions/pnpm-setup

      - name: Install dependencies
        run: pnpm install

      - name: Run PNPM Script
        run: pnpm format:check
