name: Network Check
on:
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
jobs:
  check-registry-access:
    runs-on: [prod-gen2-dind-runner]
    steps:
      - name: Pull from Docker Hub (hello-world)
        run: docker pull hello-world
        shell: bash

      - name: Pull from Docker Hub (alpine)
        run: docker pull alpine:3.21
        shell: bash

      - name: Pull from ghcr.io (publish-unit-test-result-action)
        run: docker pull ghcr.io/enricomi/publish-unit-test-result-action:v2.23.0
        shell: bash

      - name: Pull from quay.io (busybox)
        run: docker pull quay.io/prometheus/busybox:latest
        shell: bash
