name: Tests
on:
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
permissions:
  checks: write
  pull-requests: write
jobs:
  unit-tests:
    runs-on: [self-hosted, amd64-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pnpm install composite action
        uses: ./.github/actions/pnpm-install

      - name: Run unit tests
        run: pnpm test:unit

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: (!cancelled())
        with:
          check_name: 'Unit Test Results'
          files: |
            **/test-results/test-results.xml

  integration-tests:
    runs-on: [self-hosted, amd64-runner, dind-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup test environment
        uses: ./.github/actions/setup-test-env

      - name: Run dev dependencies
        run: pnpm dev:deps

      - name: Run integration tests
        run: pnpm test:int

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: (!cancelled())
        with:
          check_name: 'Integration Test Results'
          files: |
            **/test-results/test-results.xml

      - name: Stop dev dependencies
        if: always()
        run: pnpm dev:deps:down

  e2e-tests:
    runs-on: [self-hosted, amd64-runner, dind-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup test environment
        uses: ./.github/actions/setup-test-env

      - name: Start e2e dependencies
        run: pnpm e2e:deps

      - name: Run e2e tests
        run: pnpm test:e2e

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: (!cancelled())
        with:
          check_name: 'E2E Test Results'
          files: |
            **/test-results/test-results.xml

      - name: Stop e2e dependencies
        if: always()
        run: pnpm e2e:deps:down
