name: tests
on:
  workflow_dispatch: {}
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
jobs:
  unit-tests:
    uses: ./.github/workflows/reusable-pnpm-script.yml
    with:
      pnpm-script: test:unit

  integration-tests:
    runs-on: [self-hosted, amd64-runner, dind-runner]
    steps:
      - name: Checkout PR branch safely
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1

      - name: Build environment files
        run: |
          ./scripts/env-media.sh
          ./scripts/env-gluetun-sync.sh
        env:
          OP_CONNECT_HOST: https://op-connect.local.abbottland.io
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}

      - name: Run media services
        run: docker compose -f ./docker-compose.media.yml up -d --quiet-pull

      - name: pnpm install composite action
        uses: ./.github/actions/pnpm-install

      - name: Run integration tests
        run: pnpm test:int
