name: Unit, Integration, and E2E Tests
on:
  workflow_dispatch: {}
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
jobs:
  unit-tests:
    runs-on: [self-hosted, amd64-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pnpm install composite action
        uses: ./.github/actions/pnpm-install

      - name: Run unit tests
        run: pnpm test:unit

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/test-results/*.xml'

  integration-tests:
    runs-on: [self-hosted, amd64-runner, dind-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: pnpm install composite action
        uses: ./.github/actions/pnpm-install

      - name: Build environment files
        run: pnpm generate:secrets
        env:
          OP_CONNECT_HOST: https://op-connect.local.abbottland.io
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}

      - name: Run dev dependencies
        run: pnpm dev:deps

      - name: Run integration tests
        run: pnpm test:int

      - name: Stop dev dependencies
        run: pnpm dev:deps:down

  e2e-tests:
    runs-on: [self-hosted, amd64-runner, dind-runner]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: pnpm install composite action
        uses: ./.github/actions/pnpm-install

      - name: Build environment files
        run: pnpm generate:secrets
        env:
          OP_CONNECT_HOST: https://op-connect.local.abbottland.io
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}

      - name: Start e2e dependencies
        run: pnpm e2e:deps

      - name: Run e2e tests
        run: pnpm test:e2e

      - name: Stop e2e dependencies
        run: pnpm e2e:deps:down
